plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: 'templates/**'
    values:
      sitemap: false

  -
    scope:
      path: 'navbar.html'
    values:
      sitemap: false

  -
    scope:
      path: 'nojs.html'
    values:
      sitemap: false
